### ISSUE TITLE
Update harvest client to support ability to update archive status

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-harvest-service#12]
## 💡 Description

Child of NASA-PDS/pds-registry-app#223 and NASA-PDS/pds-registry-app#224

sister ticket to NASA-PDS/big-data-harvest-server#2

**Comment by tloubrieu-jpl** [comment]
This is closed per pr https://github.com/NASA-PDS/registry-harvest-service/pull/16

**Comment by tloubrieu-jpl** [comment]
I am reopening until @mdrum validates that it works.

@mdrum do you want to try the fixed release available on https://github.com/NASA-PDS/registry-harvest-service/releases/tag/v1.0.1-SNAPSHOT

Thanks,

**Comment by mdrum** [comment]
I'll check it out this week, thanks!

**Comment by tloubrieu-jpl** [comment]
Thanks @mdrum , I will create a new release with this fix.
